replicaCount: 3

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10

pdb:
  minAvailable: 2

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

secretsManager:
  dbCredentials: nutriapp/prod/catalog-service/db-credentials
  usdaFdcApiKey: nutriapp/prod/catalog-service/usda-fdc-api-key

dbProvisionJob:
  adminCredentialsSecretName: nutriapp/prod/rds/admin-credentials
  appCredentialsSecretName: nutriapp/prod/catalog-service/db-credentials
