replicaCount: 3

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10

pdb:
  minAvailable: 2

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

secretsManager:
  dbCredentials: nutriapp/prod/diary-service/db-credentials

dbProvision:
  dbCredentialSecretArn: nutriapp/prod/diary-service/db-credentials
