# infra/terraform/modules/elasticache/main.tf
#
# Single-node Redis for dev (cluster mode / multi-node is a prod
# concern). Uses aws_elasticache_replication_group (not the legacy
# aws_elasticache_cluster resource) even for a single node, because only
# the replication-group resource supports transit encryption + an auth
# token, which docs/secrets-management.md's inventory table requires
# ("Redis auth token").

locals {
  base_tags = merge(var.tags, {
    Service = "shared"
  })
}

resource "aws_elasticache_subnet_group" "this" {
  name       = "${var.name}-subnet-group"
  subnet_ids = var.private_subnet_ids

  tags = local.base_tags
}

resource "aws_security_group" "this" {
  name        = "${var.name}-redis"
  description = "Allow Redis access from the EKS cluster only."
  vpc_id      = var.vpc_id

  # No egress at all: ElastiCache itself never initiates outbound
  # connections, so egress is explicitly denied rather than left at
  # AWS's implicit allow-all default (checkov CKV_AWS_382).
  egress = []

  tags = merge(local.base_tags, {
    Name = "${var.name}-redis"
  })
}

resource "aws_security_group_rule" "ingress" {
  # `count`, not `for_each`/toset(): see the identical comment in
  # modules/rds/main.tf — var.allowed_security_group_ids's values are
  # unknown until the EKS cluster exists on a from-scratch apply.
  count                    = length(var.allowed_security_group_ids)
  type                     = "ingress"
  from_port                = var.port
  to_port                  = var.port
  protocol                 = "tcp"
  security_group_id        = aws_security_group.this.id
  source_security_group_id = var.allowed_security_group_ids[count.index]
  description              = "Redis from EKS security group ${count.index}"
}

resource "aws_elasticache_parameter_group" "this" {
  name   = "${var.name}-redis"
  family = var.parameter_group_family
}

# Auth token: generated by a resource (random_password), never a literal
# in .tf/.tfvars, and stored to Secrets Manager immediately below as the
# durable source of truth. This is the same pattern as the JWT signing
# key pair in modules/secrets (tls_private_key), and mirrors ADR-0007.
#
# KNOWN DOC/REALITY GAP (implementation plan section 9.4, not fixed by
# this plan): docs/secrets-management.md's inventory table claims this
# rotates automatically ("Automatic (ElastiCache rotation)"), but
# ElastiCache has no Secrets-Manager-native rotation Lambda the way RDS
# does. Flagged for a future doc correction or a small custom rotation
# Lambda; not blocking since the auth token isn't yet in active use by
# any service.
resource "random_password" "auth_token" {
  length  = 32
  special = false # ElastiCache AUTH tokens disallow some special characters
}

resource "aws_secretsmanager_secret" "auth_token" {
  # checkov:skip=CKV2_AWS_57:Known doc/reality gap, implementation plan section 9.4 — ElastiCache has no Secrets-Manager-native rotation Lambda the way RDS does; automating this is a follow-up (custom rotation Lambda or a docs correction), not blocking since this token isn't yet in active use by any service.
  name       = "nutriapp/shared/redis-auth-token"
  kms_key_id = var.secrets_kms_key_id

  tags = local.base_tags
}

resource "aws_secretsmanager_secret_version" "auth_token" {
  secret_id = aws_secretsmanager_secret.auth_token.id
  secret_string = jsonencode({
    auth_token = random_password.auth_token.result
  })
}

resource "aws_elasticache_replication_group" "this" {
  replication_group_id = var.name
  description          = "NutriApp shared Redis cache (${var.name})"

  engine             = "redis"
  engine_version     = var.engine_version
  node_type          = var.node_type
  num_cache_clusters = var.num_cache_clusters
  port               = var.port

  subnet_group_name    = aws_elasticache_subnet_group.this.name
  security_group_ids   = [aws_security_group.this.id]
  parameter_group_name = aws_elasticache_parameter_group.this.name

  at_rest_encryption_enabled = true
  transit_encryption_enabled = true
  auth_token                 = random_password.auth_token.result
  # checkov:skip=CKV_AWS_191:At-rest encryption uses the default AWS-owned key; a dedicated CMK is a reasonable future hardening step but disproportionate at this scale/cost posture today.

  # checkov:skip=CKV2_AWS_50:num_cache_clusters=1 (single-node) is this module's deliberate dev-cost default (docs/terraform-and-infrastructure.md section 3: "single node for dev") — Multi-AZ automatic failover requires >=2 nodes, which is a prod-sizing concern tracked separately, not this module's dev default.
  automatic_failover_enabled = false
  multi_az_enabled           = false

  apply_immediately = true

  tags = merge(local.base_tags, {
    Name = var.name
  })
}
