# infra/terraform/modules/secrets/main.tf

locals {
  base_tags = merge(var.tags, {
    Service = "shared"
  })

  oidc_provider_url_no_scheme = replace(var.oidc_provider_url, "https://", "")
}

# --- JWT signing key pairs ------------------------------------------------
# Generated by a Terraform resource (never a literal value in .tf/.tfvars,
# per CLAUDE.md section 7 and ADR-0007). The private key does live in this
# module's Terraform state, which is why remote state is encrypted-at-rest
# S3 with versioning and TLS-only access (infra/terraform/bootstrap).

resource "tls_private_key" "jwt_signing_key" {
  for_each  = toset(var.jwt_signing_key_service_names)
  algorithm = var.jwt_key_algorithm
  rsa_bits  = var.jwt_key_rsa_bits
}

resource "aws_secretsmanager_secret" "jwt_signing_key" {
  # checkov:skip=CKV2_AWS_57:ADR-0007 / docs/secrets-management.md section 1 — JWT signing key rotation is deliberately manual, every 90 days, per a documented runbook, until volume justifies automating it (there is no AWS-native rotation Lambda template for an application-defined RSA key pair the way there is for RDS master passwords).
  for_each   = toset(var.jwt_signing_key_service_names)
  name       = "nutriapp/${var.environment}/${each.value}/jwt-signing-key"
  kms_key_id = var.secrets_kms_key_id

  tags = merge(local.base_tags, {
    Name = "${each.value}-jwt-signing-key"
  })
}

resource "aws_secretsmanager_secret_version" "jwt_signing_key" {
  for_each  = toset(var.jwt_signing_key_service_names)
  secret_id = aws_secretsmanager_secret.jwt_signing_key[each.value].id
  secret_string = jsonencode({
    algorithm       = var.jwt_key_algorithm
    private_key_pem = tls_private_key.jwt_signing_key[each.value].private_key_pem
    public_key_pem  = tls_private_key.jwt_signing_key[each.value].public_key_pem
  })
}

# --- DB credential containers --------------------------------------------
# Empty (placeholder) container: the real username/password is written at
# deploy time by the service's own `_db-provision-job` Helm hook (running
# in-cluster, with write-only IRSA access scoped to exactly this ARN — see
# below). Terraform intentionally ignores drift on `secret_string` after
# the Job's first write.

resource "aws_secretsmanager_secret" "db_credentials" {
  # checkov:skip=CKV2_AWS_57:This is a Job-managed application credential (created by _db-provision-job, not RDS's own master password, which already has native rotation via manage_master_user_password), same manual-rotation posture as the JWT signing key above until volume justifies automating a custom rotation Lambda for this pattern.
  for_each   = toset(var.db_credential_service_names)
  name       = "nutriapp/${var.environment}/${each.value}/db-credentials"
  kms_key_id = var.secrets_kms_key_id

  tags = merge(local.base_tags, {
    Name = "${each.value}-db-credentials"
  })
}

resource "aws_secretsmanager_secret_version" "db_credentials_placeholder" {
  for_each  = toset(var.db_credential_service_names)
  secret_id = aws_secretsmanager_secret.db_credentials[each.value].id
  secret_string = jsonencode({
    username = "PENDING"
    password = "PENDING"
    note     = "Populated at deploy time by ${each.value}'s _db-provision-job Helm hook, not by Terraform."
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# --- Internal reveal credential (per service) ------------------------------
# Shared bearer credential for a service's internal, non-Kong-routed
# endpoints authenticated service-to-service (e.g. identity-service's
# token-reveal endpoint per docs/domain-glossary-and-context-map.md's
# reference+secret pattern — notification-service, once it exists, presents
# this value; identity-service verifies it via a constant-time comparison).
# Generated by Terraform (random_password), never a literal value.

resource "random_password" "internal_reveal_credential" {
  for_each = toset(var.internal_reveal_credential_service_names)
  length   = 32
  special  = false
}

resource "aws_secretsmanager_secret" "internal_reveal_credential" {
  # checkov:skip=CKV2_AWS_57:Same manual-rotation posture as the JWT signing key and DB credentials above — no AWS-native rotation Lambda template for an application-defined shared bearer credential, until volume justifies building a custom one.
  for_each   = toset(var.internal_reveal_credential_service_names)
  name       = "nutriapp/${var.environment}/${each.value}/internal-reveal-credential"
  kms_key_id = var.secrets_kms_key_id

  tags = merge(local.base_tags, {
    Name = "${each.value}-internal-reveal-credential"
  })
}

resource "aws_secretsmanager_secret_version" "internal_reveal_credential" {
  for_each  = toset(var.internal_reveal_credential_service_names)
  secret_id = aws_secretsmanager_secret.internal_reveal_credential[each.value].id
  secret_string = jsonencode({
    credential = random_password.internal_reveal_credential[each.value].result
    note       = "Shared bearer credential for ${each.value}'s internal, non-Kong-routed endpoint(s). Read by both the issuing service and any authorized internal caller."
  })
}

# --- Cross-service internal reveal credential (per named-caller pair) ----
# Distinct from `internal_reveal_credential` above (a single per-service
# shared secret, read only by the OWNING service itself -- no caller-side
# IRSA grant exists for it anywhere in this module). This section
# provisions a SEPARATE credential per (owner_service, caller_service)
# PAIR, each with its own Terraform `random_password` and its own narrow
# IRSA role scoped to read exactly that one secret. Required whenever an
# internal endpoint discloses Article 9 health data cross-service
# (profile-service's `reveal-metrics` endpoint, security-agent review,
# profile-service implementation plan Addendum 2) and a single shared
# secret / no-caller-specific-grant design is judged insufficient — never
# broadened into a generic "any internal caller may read any owner's
# credential" mechanism.

locals {
  cross_service_reveal_credentials_by_key = {
    for c in var.cross_service_reveal_credentials :
    "${c.owner_service}-${c.caller_service}" => c
  }
}

resource "random_password" "cross_service_reveal_credential" {
  for_each = local.cross_service_reveal_credentials_by_key
  length   = 32
  special  = false
}

resource "aws_secretsmanager_secret" "cross_service_reveal_credential" {
  # checkov:skip=CKV2_AWS_57:Same manual-rotation posture as internal_reveal_credential above -- no AWS-native rotation Lambda template for an application-defined shared bearer credential, until volume justifies building a custom one.
  for_each   = local.cross_service_reveal_credentials_by_key
  name       = "nutriapp/${var.environment}/${each.value.owner_service}/internal-reveal-credential-${each.value.caller_service}"
  kms_key_id = var.secrets_kms_key_id

  tags = merge(local.base_tags, {
    Name = "${each.value.owner_service}-internal-reveal-credential-${each.value.caller_service}"
  })
}

resource "aws_secretsmanager_secret_version" "cross_service_reveal_credential" {
  for_each  = local.cross_service_reveal_credentials_by_key
  secret_id = aws_secretsmanager_secret.cross_service_reveal_credential[each.key].id
  secret_string = jsonencode({
    credential = random_password.cross_service_reveal_credential[each.key].result
    note       = "Per-caller bearer credential: ${each.value.owner_service}'s internal reveal endpoint, presented only by ${each.value.caller_service}. Never shared with any other caller or reused across another owner service's endpoint."
  })
}

# Owner service reads this credential to verify a presented value. A
# narrow, ADDITIVE statement attached directly to that service's
# already-existing app_secrets role (by reconstructed name, same pattern
# environments/dev/profile-service.tf already uses for its KMS grant) --
# deliberately not folded into the generic `app_secrets` for_each policy
# document above, which every `db_credential_service_names` member shares
# the *shape* of but not this specific resource.
data "aws_iam_policy_document" "cross_service_reveal_credential_owner_read" {
  for_each = local.cross_service_reveal_credentials_by_key

  statement {
    sid    = "ReadOwnCrossServiceRevealCredential"
    effect = "Allow"
    actions = [
      "secretsmanager:GetSecretValue",
      "secretsmanager:DescribeSecret",
    ]
    resources = [aws_secretsmanager_secret.cross_service_reveal_credential[each.key].arn]
  }
}

resource "aws_iam_role_policy" "cross_service_reveal_credential_owner_read" {
  for_each = local.cross_service_reveal_credentials_by_key
  name     = "internal-reveal-credential-${each.value.caller_service}-owner-read"
  role     = "nutriapp-${var.environment}-${each.value.owner_service}-app-secrets"
  policy   = data.aws_iam_policy_document.cross_service_reveal_credential_owner_read[each.key].json
}

# Caller service's IRSA role -- a NEW, narrowly-scoped role dedicated to
# exactly this one grant (NOT the caller's own app_secrets role, which, if
# it exists at all, is defined in that service's own Terraform file --
# potentially a concurrently-developed, not-yet-reconciled plan/worktree,
# exactly like identity-service.tf/platform-infra's documented output-name
# reconciliation precedent). Trusts only the caller's own ServiceAccount
# name in the shared namespace. The caller's own chart/Terraform wires
# this role's ARN in directly, OR — at /implementation-review reconciliation
# — this single statement is merged into whatever role that service's own
# app pod already assumes, so a ServiceAccount only ever needs exactly one
# IRSA role annotation.
data "aws_iam_policy_document" "cross_service_reveal_credential_caller_assume" {
  for_each = local.cross_service_reveal_credentials_by_key

  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    principals {
      type        = "Federated"
      identifiers = [var.oidc_provider_arn]
    }

    condition {
      test     = "StringEquals"
      variable = "${local.oidc_provider_url_no_scheme}:sub"
      values   = ["system:serviceaccount:${var.namespace}:${each.value.caller_service}"]
    }

    condition {
      test     = "StringEquals"
      variable = "${local.oidc_provider_url_no_scheme}:aud"
      values   = ["sts.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "cross_service_reveal_credential_caller" {
  for_each           = local.cross_service_reveal_credentials_by_key
  name               = "nutriapp-${var.environment}-${each.value.caller_service}-read-${each.value.owner_service}-reveal-credential"
  assume_role_policy = data.aws_iam_policy_document.cross_service_reveal_credential_caller_assume[each.key].json

  tags = local.base_tags
}

data "aws_iam_policy_document" "cross_service_reveal_credential_caller_read" {
  for_each = local.cross_service_reveal_credentials_by_key

  statement {
    sid    = "ReadExactlyOneCrossServiceRevealCredential"
    effect = "Allow"
    actions = [
      "secretsmanager:GetSecretValue",
    ]
    resources = [aws_secretsmanager_secret.cross_service_reveal_credential[each.key].arn]
  }
}

resource "aws_iam_role_policy" "cross_service_reveal_credential_caller_read" {
  for_each = local.cross_service_reveal_credentials_by_key
  name     = "read-reveal-credential"
  role     = aws_iam_role.cross_service_reveal_credential_caller[each.key].id
  policy   = data.aws_iam_policy_document.cross_service_reveal_credential_caller_read[each.key].json
}

# --- USDA FoodData Central API key (per service) --------------------------
# Empty (placeholder) container, same shape as db_credentials above: this
# value is a genuine external, third-party-issued secret (a free
# registered key from https://fdc.nal.usda.gov/api-key-signup.html) that
# cannot be Terraform-generated -- it must be written into this container
# manually (out-of-band, e.g. `aws secretsmanager put-secret-value`) by
# whoever registers the key, before catalog-service's first real (rather
# than DEMO_KEY smoke-test) ingestion run. Terraform intentionally ignores
# drift on `secret_string` after that manual write, exactly like
# db_credentials.

resource "aws_secretsmanager_secret" "usda_fdc_api_key" {
  # checkov:skip=CKV2_AWS_57:Externally-issued third-party API key, manually rotated per a documented runbook -- no AWS-native rotation Lambda template applies to a USDA-issued credential.
  for_each   = toset(var.usda_fdc_api_key_service_names)
  name       = "nutriapp/${var.environment}/${each.value}/usda-fdc-api-key"
  kms_key_id = var.secrets_kms_key_id

  tags = merge(local.base_tags, {
    Name = "${each.value}-usda-fdc-api-key"
  })
}

resource "aws_secretsmanager_secret_version" "usda_fdc_api_key_placeholder" {
  for_each  = toset(var.usda_fdc_api_key_service_names)
  secret_id = aws_secretsmanager_secret.usda_fdc_api_key[each.value].id
  secret_string = jsonencode({
    api_key = "PENDING"
    note    = "Populated manually, out-of-band, with a real key registered at https://fdc.nal.usda.gov/api-key-signup.html -- never by Terraform."
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# --- Anthropic API key (per service) ---------------------------------------
# Empty (placeholder) container, same shape as usda_fdc_api_key above: a
# genuine external, third-party-issued, METERED secret (food-recognition-
# service implementation plan section 6(b)) that cannot be
# Terraform-generated -- it must be written into this container manually
# (out-of-band) by whoever provisions an Anthropic Console API key, before
# food-recognition-service's first real (non-fixture) vision call.
# Terraform intentionally ignores drift on `secret_string` after that
# manual write, exactly like db_credentials/usda_fdc_api_key.

resource "aws_secretsmanager_secret" "anthropic_api_key" {
  # checkov:skip=CKV2_AWS_57:Externally-issued third-party API key, manually rotated per a documented runbook -- no AWS-native rotation Lambda template applies to an Anthropic-issued credential.
  for_each   = toset(var.anthropic_api_key_service_names)
  name       = "nutriapp/${var.environment}/${each.value}/anthropic-api-key"
  kms_key_id = var.secrets_kms_key_id

  tags = merge(local.base_tags, {
    Name = "${each.value}-anthropic-api-key"
  })
}

resource "aws_secretsmanager_secret_version" "anthropic_api_key_placeholder" {
  for_each  = toset(var.anthropic_api_key_service_names)
  secret_id = aws_secretsmanager_secret.anthropic_api_key[each.value].id
  secret_string = jsonencode({
    api_key = "PENDING"
    note    = "Populated manually, out-of-band, with a real Anthropic Console API key -- never by Terraform."
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# --- Stripe secret API key (per service) -----------------------------------
# Empty (placeholder) container, same shape as anthropic_api_key above: a
# genuine external, third-party-issued secret (billing-service implementation
# plan section 1, ADR-0015) that cannot be Terraform-generated -- it must be
# written into this container manually (out-of-band) once a real Stripe
# account/API key is provisioned (a tracked lead-time item, not a blocker to
# this module). Terraform intentionally ignores drift on `secret_string`
# after that manual write, exactly like anthropic_api_key/usda_fdc_api_key.

resource "aws_secretsmanager_secret" "stripe_api_key" {
  # checkov:skip=CKV2_AWS_57:Externally-issued third-party API key, manually rotated per a documented runbook -- no AWS-native rotation Lambda template applies to a Stripe-issued credential.
  for_each   = toset(var.stripe_api_key_service_names)
  name       = "nutriapp/${var.environment}/${each.value}/stripe-api-key"
  kms_key_id = var.secrets_kms_key_id

  tags = merge(local.base_tags, {
    Name = "${each.value}-stripe-api-key"
  })
}

resource "aws_secretsmanager_secret_version" "stripe_api_key_placeholder" {
  for_each  = toset(var.stripe_api_key_service_names)
  secret_id = aws_secretsmanager_secret.stripe_api_key[each.value].id
  secret_string = jsonencode({
    secret_key = "PENDING"
    note       = "Populated manually, out-of-band, with a real Stripe secret key -- never by Terraform."
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# --- Stripe webhook signing secret (per service) ----------------------------
# Same externally-issued-secret shape as stripe_api_key above -- populated
# manually, out-of-band, once the webhook endpoint is registered in the
# Stripe dashboard and Stripe issues a `whsec_...` signing secret
# (billing-service implementation plan section 1.2).

resource "aws_secretsmanager_secret" "stripe_webhook_signing_secret" {
  # checkov:skip=CKV2_AWS_57:Externally-issued third-party webhook signing secret, manually rotated per a documented runbook -- no AWS-native rotation Lambda template applies to a Stripe-issued credential.
  for_each   = toset(var.stripe_webhook_signing_secret_service_names)
  name       = "nutriapp/${var.environment}/${each.value}/stripe-webhook-signing-secret"
  kms_key_id = var.secrets_kms_key_id

  tags = merge(local.base_tags, {
    Name = "${each.value}-stripe-webhook-signing-secret"
  })
}

resource "aws_secretsmanager_secret_version" "stripe_webhook_signing_secret_placeholder" {
  for_each  = toset(var.stripe_webhook_signing_secret_service_names)
  secret_id = aws_secretsmanager_secret.stripe_webhook_signing_secret[each.value].id
  secret_string = jsonencode({
    signing_secret = "PENDING"
    note           = "Populated manually, out-of-band, with the real whsec_... value Stripe issues when the webhook endpoint is registered -- never by Terraform."
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# --- IRSA: db-provision-job (write-only, per service) ---------------------
# Trust policy binds to "<service>-db-provision" ServiceAccount in the
# shared namespace — the consuming Helm chart's Job must use exactly this
# ServiceAccount name (infra/k8s/charts/_lib/README.md).

data "aws_iam_policy_document" "db_provision_assume" {
  for_each = toset(var.db_credential_service_names)

  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    principals {
      type        = "Federated"
      identifiers = [var.oidc_provider_arn]
    }

    condition {
      test     = "StringEquals"
      variable = "${local.oidc_provider_url_no_scheme}:sub"
      values   = ["system:serviceaccount:${var.namespace}:${each.value}-db-provision"]
    }

    condition {
      test     = "StringEquals"
      variable = "${local.oidc_provider_url_no_scheme}:aud"
      values   = ["sts.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "db_provision" {
  for_each           = toset(var.db_credential_service_names)
  name               = "nutriapp-${var.environment}-${each.value}-db-provision"
  assume_role_policy = data.aws_iam_policy_document.db_provision_assume[each.value].json

  tags = local.base_tags
}

data "aws_iam_policy_document" "db_provision" {
  for_each = toset(var.db_credential_service_names)

  statement {
    sid    = "WriteOwnDbCredentialSecret"
    effect = "Allow"
    actions = [
      "secretsmanager:PutSecretValue",
      "secretsmanager:DescribeSecret",
    ]
    resources = [aws_secretsmanager_secret.db_credentials[each.value].arn]
  }

  statement {
    sid    = "ReadRdsMasterCredentialToConnect"
    effect = "Allow"
    actions = [
      "secretsmanager:GetSecretValue",
    ]
    resources = [var.rds_master_user_secret_arn]
  }
}

resource "aws_iam_role_policy" "db_provision" {
  for_each = toset(var.db_credential_service_names)
  name     = "db-provision"
  role     = aws_iam_role.db_provision[each.value].id
  policy   = data.aws_iam_policy_document.db_provision[each.value].json
}

# --- IRSA: app runtime (read-only, per service) ---------------------------
# Trust policy binds to "<service>" ServiceAccount (the app Deployment's
# own SA, distinct from the Job's) — least privilege per
# docs/secrets-management.md section 4: no shared "god" role that can
# read every service's secrets.

data "aws_iam_policy_document" "app_secrets_assume" {
  for_each = toset(var.db_credential_service_names)

  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    principals {
      type        = "Federated"
      identifiers = [var.oidc_provider_arn]
    }

    condition {
      test     = "StringEquals"
      variable = "${local.oidc_provider_url_no_scheme}:sub"
      values   = ["system:serviceaccount:${var.namespace}:${each.value}"]
    }

    condition {
      test     = "StringEquals"
      variable = "${local.oidc_provider_url_no_scheme}:aud"
      values   = ["sts.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "app_secrets" {
  for_each           = toset(var.db_credential_service_names)
  name               = "nutriapp-${var.environment}-${each.value}-app-secrets"
  assume_role_policy = data.aws_iam_policy_document.app_secrets_assume[each.value].json

  tags = local.base_tags
}

data "aws_iam_policy_document" "app_secrets" {
  for_each = toset(var.db_credential_service_names)

  statement {
    sid    = "ReadOwnSecretsOnly"
    effect = "Allow"
    actions = [
      "secretsmanager:GetSecretValue",
      "secretsmanager:DescribeSecret",
    ]
    resources = compact([
      aws_secretsmanager_secret.db_credentials[each.value].arn,
      contains(var.jwt_signing_key_service_names, each.value) ? aws_secretsmanager_secret.jwt_signing_key[each.value].arn : "",
      contains(var.internal_reveal_credential_service_names, each.value) ? aws_secretsmanager_secret.internal_reveal_credential[each.value].arn : "",
      contains(var.usda_fdc_api_key_service_names, each.value) ? aws_secretsmanager_secret.usda_fdc_api_key[each.value].arn : "",
      contains(var.anthropic_api_key_service_names, each.value) ? aws_secretsmanager_secret.anthropic_api_key[each.value].arn : "",
      contains(var.stripe_api_key_service_names, each.value) ? aws_secretsmanager_secret.stripe_api_key[each.value].arn : "",
      contains(var.stripe_webhook_signing_secret_service_names, each.value) ? aws_secretsmanager_secret.stripe_webhook_signing_secret[each.value].arn : "",
    ])
  }
}

resource "aws_iam_role_policy" "app_secrets" {
  for_each = toset(var.db_credential_service_names)
  name     = "app-secrets-read"
  role     = aws_iam_role.app_secrets[each.value].id
  policy   = data.aws_iam_policy_document.app_secrets[each.value].json
}
