# infra/terraform/modules/secrets/main.tf

locals {
  base_tags = merge(var.tags, {
    Service = "shared"
  })

  oidc_provider_url_no_scheme = replace(var.oidc_provider_url, "https://", "")
}

# --- JWT signing key pairs ------------------------------------------------
# Generated by a Terraform resource (never a literal value in .tf/.tfvars,
# per CLAUDE.md section 7 and ADR-0007). The private key does live in this
# module's Terraform state, which is why remote state is encrypted-at-rest
# S3 with versioning and TLS-only access (infra/terraform/bootstrap).

resource "tls_private_key" "jwt_signing_key" {
  for_each  = toset(var.jwt_signing_key_service_names)
  algorithm = var.jwt_key_algorithm
  rsa_bits  = var.jwt_key_rsa_bits
}

resource "aws_secretsmanager_secret" "jwt_signing_key" {
  # checkov:skip=CKV2_AWS_57:ADR-0007 / docs/secrets-management.md section 1 — JWT signing key rotation is deliberately manual, every 90 days, per a documented runbook, until volume justifies automating it (there is no AWS-native rotation Lambda template for an application-defined RSA key pair the way there is for RDS master passwords).
  for_each   = toset(var.jwt_signing_key_service_names)
  name       = "nutriapp/${var.environment}/${each.value}/jwt-signing-key"
  kms_key_id = var.secrets_kms_key_id

  tags = merge(local.base_tags, {
    Name = "${each.value}-jwt-signing-key"
  })
}

resource "aws_secretsmanager_secret_version" "jwt_signing_key" {
  for_each  = toset(var.jwt_signing_key_service_names)
  secret_id = aws_secretsmanager_secret.jwt_signing_key[each.value].id
  secret_string = jsonencode({
    algorithm       = var.jwt_key_algorithm
    private_key_pem = tls_private_key.jwt_signing_key[each.value].private_key_pem
    public_key_pem  = tls_private_key.jwt_signing_key[each.value].public_key_pem
  })
}

# --- DB credential containers --------------------------------------------
# Empty (placeholder) container: the real username/password is written at
# deploy time by the service's own `_db-provision-job` Helm hook (running
# in-cluster, with write-only IRSA access scoped to exactly this ARN — see
# below). Terraform intentionally ignores drift on `secret_string` after
# the Job's first write.

resource "aws_secretsmanager_secret" "db_credentials" {
  # checkov:skip=CKV2_AWS_57:This is a Job-managed application credential (created by _db-provision-job, not RDS's own master password, which already has native rotation via manage_master_user_password), same manual-rotation posture as the JWT signing key above until volume justifies automating a custom rotation Lambda for this pattern.
  for_each   = toset(var.db_credential_service_names)
  name       = "nutriapp/${var.environment}/${each.value}/db-credentials"
  kms_key_id = var.secrets_kms_key_id

  tags = merge(local.base_tags, {
    Name = "${each.value}-db-credentials"
  })
}

resource "aws_secretsmanager_secret_version" "db_credentials_placeholder" {
  for_each  = toset(var.db_credential_service_names)
  secret_id = aws_secretsmanager_secret.db_credentials[each.value].id
  secret_string = jsonencode({
    username = "PENDING"
    password = "PENDING"
    note     = "Populated at deploy time by ${each.value}'s _db-provision-job Helm hook, not by Terraform."
  })

  lifecycle {
    ignore_changes = [secret_string]
  }
}

# --- Internal reveal credential (per service) ------------------------------
# Shared bearer credential for a service's internal, non-Kong-routed
# endpoints authenticated service-to-service (e.g. identity-service's
# token-reveal endpoint per docs/domain-glossary-and-context-map.md's
# reference+secret pattern — notification-service, once it exists, presents
# this value; identity-service verifies it via a constant-time comparison).
# Generated by Terraform (random_password), never a literal value.

resource "random_password" "internal_reveal_credential" {
  for_each = toset(var.internal_reveal_credential_service_names)
  length   = 32
  special  = false
}

resource "aws_secretsmanager_secret" "internal_reveal_credential" {
  # checkov:skip=CKV2_AWS_57:Same manual-rotation posture as the JWT signing key and DB credentials above — no AWS-native rotation Lambda template for an application-defined shared bearer credential, until volume justifies building a custom one.
  for_each   = toset(var.internal_reveal_credential_service_names)
  name       = "nutriapp/${var.environment}/${each.value}/internal-reveal-credential"
  kms_key_id = var.secrets_kms_key_id

  tags = merge(local.base_tags, {
    Name = "${each.value}-internal-reveal-credential"
  })
}

resource "aws_secretsmanager_secret_version" "internal_reveal_credential" {
  for_each  = toset(var.internal_reveal_credential_service_names)
  secret_id = aws_secretsmanager_secret.internal_reveal_credential[each.value].id
  secret_string = jsonencode({
    credential = random_password.internal_reveal_credential[each.value].result
    note       = "Shared bearer credential for ${each.value}'s internal, non-Kong-routed endpoint(s). Read by both the issuing service and any authorized internal caller."
  })
}

# --- IRSA: db-provision-job (write-only, per service) ---------------------
# Trust policy binds to "<service>-db-provision" ServiceAccount in the
# shared namespace — the consuming Helm chart's Job must use exactly this
# ServiceAccount name (infra/k8s/charts/_lib/README.md).

data "aws_iam_policy_document" "db_provision_assume" {
  for_each = toset(var.db_credential_service_names)

  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    principals {
      type        = "Federated"
      identifiers = [var.oidc_provider_arn]
    }

    condition {
      test     = "StringEquals"
      variable = "${local.oidc_provider_url_no_scheme}:sub"
      values   = ["system:serviceaccount:${var.namespace}:${each.value}-db-provision"]
    }

    condition {
      test     = "StringEquals"
      variable = "${local.oidc_provider_url_no_scheme}:aud"
      values   = ["sts.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "db_provision" {
  for_each           = toset(var.db_credential_service_names)
  name               = "nutriapp-${var.environment}-${each.value}-db-provision"
  assume_role_policy = data.aws_iam_policy_document.db_provision_assume[each.value].json

  tags = local.base_tags
}

data "aws_iam_policy_document" "db_provision" {
  for_each = toset(var.db_credential_service_names)

  statement {
    sid    = "WriteOwnDbCredentialSecret"
    effect = "Allow"
    actions = [
      "secretsmanager:PutSecretValue",
      "secretsmanager:DescribeSecret",
    ]
    resources = [aws_secretsmanager_secret.db_credentials[each.value].arn]
  }

  statement {
    sid    = "ReadRdsMasterCredentialToConnect"
    effect = "Allow"
    actions = [
      "secretsmanager:GetSecretValue",
    ]
    resources = [var.rds_master_user_secret_arn]
  }
}

resource "aws_iam_role_policy" "db_provision" {
  for_each = toset(var.db_credential_service_names)
  name     = "db-provision"
  role     = aws_iam_role.db_provision[each.value].id
  policy   = data.aws_iam_policy_document.db_provision[each.value].json
}

# --- IRSA: app runtime (read-only, per service) ---------------------------
# Trust policy binds to "<service>" ServiceAccount (the app Deployment's
# own SA, distinct from the Job's) — least privilege per
# docs/secrets-management.md section 4: no shared "god" role that can
# read every service's secrets.

data "aws_iam_policy_document" "app_secrets_assume" {
  for_each = toset(var.db_credential_service_names)

  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRoleWithWebIdentity"]

    principals {
      type        = "Federated"
      identifiers = [var.oidc_provider_arn]
    }

    condition {
      test     = "StringEquals"
      variable = "${local.oidc_provider_url_no_scheme}:sub"
      values   = ["system:serviceaccount:${var.namespace}:${each.value}"]
    }

    condition {
      test     = "StringEquals"
      variable = "${local.oidc_provider_url_no_scheme}:aud"
      values   = ["sts.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "app_secrets" {
  for_each           = toset(var.db_credential_service_names)
  name               = "nutriapp-${var.environment}-${each.value}-app-secrets"
  assume_role_policy = data.aws_iam_policy_document.app_secrets_assume[each.value].json

  tags = local.base_tags
}

data "aws_iam_policy_document" "app_secrets" {
  for_each = toset(var.db_credential_service_names)

  statement {
    sid    = "ReadOwnSecretsOnly"
    effect = "Allow"
    actions = [
      "secretsmanager:GetSecretValue",
      "secretsmanager:DescribeSecret",
    ]
    resources = compact([
      aws_secretsmanager_secret.db_credentials[each.value].arn,
      contains(var.jwt_signing_key_service_names, each.value) ? aws_secretsmanager_secret.jwt_signing_key[each.value].arn : "",
      contains(var.internal_reveal_credential_service_names, each.value) ? aws_secretsmanager_secret.internal_reveal_credential[each.value].arn : "",
    ])
  }
}

resource "aws_iam_role_policy" "app_secrets" {
  for_each = toset(var.db_credential_service_names)
  name     = "app-secrets-read"
  role     = aws_iam_role.app_secrets[each.value].id
  policy   = data.aws_iam_policy_document.app_secrets[each.value].json
}
