replicaCount: 3

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10

pdb:
  minAvailable: 2

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi

secretsManager:
  dbCredentials: nutriapp/prod/billing-service/db-credentials
  stripeApiKey: nutriapp/prod/billing-service/stripe-api-key
  stripeWebhookSigningSecret: nutriapp/prod/billing-service/stripe-webhook-signing-secret
  internalEntitlementCredential: nutriapp/prod/billing-service/internal-reveal-credential

dbProvisionJob:
  adminCredentialsSecretName: nutriapp/prod/rds/admin-credentials
  appCredentialsSecretName: nutriapp/prod/billing-service/db-credentials
